//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForecastDBEntities : DbContext
    {
        public ForecastDBEntities()
            : base("name=ForecastDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AuditLogs> tbl_AuditLogs { get; set; }
        public virtual DbSet<tbl_ForecastDetails> tbl_ForecastDetails { get; set; }
        public virtual DbSet<tbl_ForecastItems> tbl_ForecastItems { get; set; }
        public virtual DbSet<tbl_ForecastRevisions> tbl_ForecastRevisions { get; set; }
        public virtual DbSet<tbl_Forecasts> tbl_Forecasts { get; set; }
        public virtual DbSet<tbl_GroupRoles> tbl_GroupRoles { get; set; }
        public virtual DbSet<tbl_UserGroups> tbl_UserGroups { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_UsersInGroups> tbl_UsersInGroups { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
