//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ForecastDBEntities : DbContext
    {
        public ForecastDBEntities()
            : base("name=ForecastDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gp_InventoryItems> gp_InventoryItems { get; set; }
        public virtual DbSet<tbl_AuditLogs> tbl_AuditLogs { get; set; }
        public virtual DbSet<tbl_ForecastDetails> tbl_ForecastDetails { get; set; }
        public virtual DbSet<tbl_ForecastItems> tbl_ForecastItems { get; set; }
        public virtual DbSet<tbl_ForecastRevisionDetails> tbl_ForecastRevisionDetails { get; set; }
        public virtual DbSet<tbl_ForecastRevisions> tbl_ForecastRevisions { get; set; }
        public virtual DbSet<tbl_Forecasts> tbl_Forecasts { get; set; }
        public virtual DbSet<tbl_GroupRoles> tbl_GroupRoles { get; set; }
        public virtual DbSet<tbl_UserGroups> tbl_UserGroups { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_UsersInGroups> tbl_UsersInGroups { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
    
        public virtual int AAA2018_CONSUMER_REPORT(string vendorItemId, Nullable<int> year, Nullable<int> month)
        {
            var vendorItemIdParameter = vendorItemId != null ?
                new ObjectParameter("VendorItemId", vendorItemId) :
                new ObjectParameter("VendorItemId", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AAA2018_CONSUMER_REPORT", vendorItemIdParameter, yearParameter, monthParameter);
        }
    
        [DbFunction("ForecastDBEntities", "AAA2018_GET_FORECAST_SUMMARY_DATA")]
        public virtual IQueryable<AAA2018_GET_FORECAST_SUMMARY_DATA_Result> AAA2018_GET_FORECAST_SUMMARY_DATA(Nullable<int> forecastId)
        {
            var forecastIdParameter = forecastId.HasValue ?
                new ObjectParameter("ForecastId", forecastId) :
                new ObjectParameter("ForecastId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<AAA2018_GET_FORECAST_SUMMARY_DATA_Result>("[ForecastDBEntities].[AAA2018_GET_FORECAST_SUMMARY_DATA](@ForecastId)", forecastIdParameter);
        }
    
        [DbFunction("ForecastDBEntities", "AAA2018_GPITEM_SYNC_ERRORS")]
        public virtual IQueryable<AAA2018_GPITEM_SYNC_ERRORS_Result> AAA2018_GPITEM_SYNC_ERRORS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<AAA2018_GPITEM_SYNC_ERRORS_Result>("[ForecastDBEntities].[AAA2018_GPITEM_SYNC_ERRORS]()");
        }
    
        public virtual ObjectResult<AAA2018_SYNC_GP_ITEMS_Result> AAA2018_SYNC_GP_ITEMS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AAA2018_SYNC_GP_ITEMS_Result>("AAA2018_SYNC_GP_ITEMS");
        }
    
        [DbFunction("ForecastDBEntities", "AAA2018_CONSUMER_REPORT_DATA")]
        public virtual IQueryable<AAA2018_CONSUMER_REPORT_DATA_Result> AAA2018_CONSUMER_REPORT_DATA(string vendorItemId, Nullable<int> year, Nullable<int> month)
        {
            var vendorItemIdParameter = vendorItemId != null ?
                new ObjectParameter("VendorItemId", vendorItemId) :
                new ObjectParameter("VendorItemId", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<AAA2018_CONSUMER_REPORT_DATA_Result>("[ForecastDBEntities].[AAA2018_CONSUMER_REPORT_DATA](@VendorItemId, @Year, @Month)", vendorItemIdParameter, yearParameter, monthParameter);
        }
    }
}
