//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gp_InventoryItems
    {
        public int ItemId { get; set; }
        public string ITEMNMBR { get; set; }
        public string ITEMDESC { get; set; }
        public Nullable<decimal> ITEMSHWT { get; set; }
        public string VENDORID { get; set; }
        public string VNDITNUM { get; set; }
        public string VNDITDSC { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<bool> CustomItem { get; set; }
        public Nullable<bool> Synced { get; set; }
    }
}
