//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ForecastRevisionDetails
    {
        public int RevisionDetailId { get; set; }
        public Nullable<int> RevisionId { get; set; }
        public string GPCustomerNumber { get; set; }
        public Nullable<decimal> ForecastValue { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
