//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ForecastDetails
    {
        public int ForecastDetailId { get; set; }
        public Nullable<int> RevisionId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> ForecastValue { get; set; }
        public Nullable<int> PreviousYearConsumption { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
