//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RevisedForecastHistory
    {
        public int RevisedForecastValueId { get; set; }
        public Nullable<int> ForecastItemId { get; set; }
        public Nullable<decimal> RevisedValue { get; set; }
        public Nullable<System.DateTime> RevisedDate { get; set; }
        public Nullable<int> RevisedBy { get; set; }
        public string Details { get; set; }
    }
}
